import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import { Mic } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClerkProvider>
          <header className="px-4 lg:px-6 h-16 flex items-center bg-[#1E3A8A]">
            <Link className="flex items-center justify-center" href="#">
              <Mic className="h-6 w-6 text-white" />
              <span className="ml-2 text-2xl font-bold text-white">
                AI Task Reminder
              </span>
            </Link>
            <nav className="ml-auto flex items-center gap-4 sm:gap-6">
              <Link
                className="text-sm font-medium hover:underline text-white"
                href="#features"
              >
                Features
              </Link>
              <Link
                className="text-sm font-medium hover:underline text-white"
                href="#how-it-works"
              >
                How It Works
              </Link>
              <Link
                className="text-sm font-medium hover:underline text-white"
                href="#contact"
              >
                Contact
              </Link>
              <SignedOut>
                <SignInButton>
                  <Button variant="outline">Sign In</Button>
                </SignInButton>
              </SignedOut>
              <SignedIn>
                <UserButton>
                  <Button variant="outline">Sign Out</Button>
                </UserButton>
              </SignedIn>
            </nav>
          </header>
        </ClerkProvider>
        {children}
      </body>
    </html>
  );
}
